spring:
  datasource:
    password: seeds
    url: jdbc:mysql://localhost:3306/seeds
    username: seeds
  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
